### ISSUE TITLE
빈 화면 오류

### ISSUE THREAD

**Issue by hyh050** [hyh050/bentolio-portfolio#5]
Avatar for Helpy Zero
아래와 같이 깃허브 저장소의 이슈에 올릴 수 있도록, hyh050.github.io/bentolio-portfolio/ 사이트의 오류 상황을 정리해드립니다.
문제 상황
깃허브 Pages로 배포된 사이트(https://hyh050.github.io/bentolio-portfolio/)에 접속하면
디자인이 적용된 웹사이트가 정상적으로 보이지 않거나,
화면에 텍스트, 링크, 소스 코드만 노출되거나,
빈 화면 또는 오류 메시지가 표시됩니다.
원인(추정)
React 프로젝트의 빌드 결과물이 정상적으로 배포되지 않았거나,
package.json, 빌드/배포 스크립트, 워크플로우 설정 등이 누락/오류일 수 있음
public, src 폴더 구조 또는 파일 경로가 잘못되었을 수 있음
GitHub Actions 또는 gh-pages 배포 과정에서 에러가 발생했을 수 있음
확인/조치 필요
로컬에서 npm run build로 정상적으로 build 폴더가 생성되는지 확인
package.json, gh-pages, homepage, deploy 스크립트 등 설정 확인
.github/workflows/ 폴더에 자동 배포(yml) 파일이 있는지 확인
GitHub Actions의 에러 로그 확인
src, public 폴더 및 주요 파일(App.jsx, index.js 등) 누락 여부 확인
요청 사항
사이트가 정상적으로 보이도록 빌드/배포 환경을 점검 및 수정해 주세요.
필요하다면 에러 로그 또는 추가 오류 메시지를 이슈에 남기겠습니다.

**Comment by hyh050** [comment]
이슈 확인: 깃허브 Pages로 배포된 사이트에 접속 시 빈 화면 또는 디자인 미적용 현상이 발생합니다.

확인 결과:
- src, public, package.json 등 주요 파일과 폴더 구조는 정상적으로 존재합니다.
- gh-pages, homepage, deploy 스크립트 등도 package.json에 정상적으로 설정되어 있습니다.
- 하지만 .github/workflows/react-deploy.yml(자동 배포용 워크플로우 파일)이 저장소에 존재하지 않아, GitHub Actions를 통한 자동 빌드/배포가 이루어지지 않고 있습니다.

해결 방법:
1. .github/workflows/react-deploy.yml 파일을 아래와 같이 추가해 주세요:

```yaml
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2. 파일 추가 후 main 브랜치에 push하면 자동으로 빌드/배포가 실행되어 빈 화면 문제가 해결됩니다.

이슈를 close 처리합니다. 추가 문제가 있으면 언제든 말씀해 주세요.
